### ISSUE TITLE
Support for macOS

### ISSUE THREAD

**Issue by andraghetti** [DoubleDeez/UnrealFastNoise2#5]
Hi!

Thank you for this plugin! Really useful!

I would like to expand it adding support for macOS. Can you tell me briefly how to achieve that?

Thank you!

**Comment by DoubleDeez** [comment]
Hey, I don't have a mac to test on but my post on how to (maybe) get it working for Android should apply to Mac as well: https://github.com/DoubleDeez/UnrealFastNoise2/issues/4#issuecomment-1550096795

Let me know how it goes

**Comment by andraghetti** [comment]
Oh yes, thanks, sorry I'm not used to cmake. This is how to make it work:

- `cmake -S . -B build -D FASTNOISE2_NOISETOOL=OFF -D FASTNOISE2_TESTS=OFF -D BUILD_SHARED_LIBS=ON`
- `cmake --build build --config release`

But the problem now is that I get files that are not `ddl`s.
```
~> ls build/lib
libCorradeUtility.a          libMagnumImGuiIntegration.a
libFastNoise.a               libMagnumSceneGraph.a
libFastNoise.dylib*          libMagnumShaders.a
libMagnum.a                  libglfw3.a
libMagnumGL.a                libimnodes.a
libMagnumGlfwApplication.a
```

So I think you need to support that name as well:

> macOS: Dynamic libraries on macOS typically have the file extension ".dylib" (e.g., "libFastNoise.dylib"). 
    Windows: Dynamic libraries on Windows have the file extension ".dll" (e.g., "FastNoise.dll").

**Comment by DoubleDeez** [comment]
Okay I made a new branch (https://github.com/DoubleDeez/UnrealFastNoise2/tree/multi-platform-support) with some changes to [FastNoise2.build.cs](https://github.com/DoubleDeez/UnrealFastNoise2/blob/multi-platform-support/Source/ThirdParty/FastNoise2/FastNoise2.build.cs) that will hopefully support Mac (and iOS and Android).

I've added the binaries for Mac (and linux) so you should only need to pull the branch and try building. Let me know how that goes @andraghetti

**Comment by andraghetti** [comment]
Thanks for your effort and sorry for the late response! I ended up using [this plugin](https://github.com/caseymcc/UE4CMake/pulls) so I could build the original FastNoise2 and link it automatically without having the binaries saved in a usually gitignored folder (`Binaries`). 

Anyway, your branch works so I think we can close this.

**Comment by DoubleDeez** [comment]
Thanks for verifying!
